rewrite `install`
besides bringing this script up to snuff,
this unifies backups created by `install`
to match `update`, for use with `rcdiff`.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,106 +1,99 @@
 #!/usr/bin/env sh
 # for busybox ash, dash, bash, and zsh.
-set -efuC && unset CDPATH IFS
-NAME="$0"
-VERBOSE="${VERBOSE-1}"
+set -Cefu && unset CDPATH IFS
+program=$0
+VERBOSE=${VERBOSE-1}
 
 die() {
-    printf '%s:' "$NAME"
+    printf '%s:' "$program"
     printf ' %s' "$@"
     printf '\n'
     exit 1
 } >&2
 
-pl() { # print lines
-    printf '%s\n' "$@"
+list_files() {
+    find "${1:-.}" -maxdepth 1 -printf '%P\n'
 }
 
-backup() {
-    : "${1:?missing argument}"
-    pl "backing up $1"
-    set -- "$1" "${backup_dir:?backup_dir unset}" # shorthand for my own sanity
-    [ -d "$2" ] || mkdir -- "$2" || die "failed to create backup directory"
-    if [ ${1%/*} != "$1" ]; then
-        mkdir -p -- "$2/${1%/*}" || die "failed to create backup directory"
-    fi
-    ! [ -e "$2/$1" ] || die "backup already exists: $2/$1"
-    mv "$1" "$2/$1" || die "failed to backup $1"
+stash() {
+    : "${1:?missing src}" # noted for its path
+    : "${2:?missing dst}" # the file to backup
+    printf '%s\n' "backing up $2"
+    set -- "${backup_dir:?parameter null or not set}/${1#"$rc"}" "$2"
+    mkdir -p -- "${1%/*}" || die "failed to create backup directory"
+    ! [ -e "$1" ] || die "backup already exists: $1"
+    mv -- "$2" "$1" || die "failed to backup $1"
 }
 
 hardlink() {
-    : "${1:?missing argument}"
-    : "${2:?missing argument}"
-    if [ -e "$1" ]; then
+    : "${1:?missing src}"
+    : "${2:?missing dst}"
+    if [ -e "$2" ]; then
         ! [ "$1" -ef "$2" ] || return 0
-        if [ -h "$1" ]; then
-            pl "removing symbolic link $1"
-            rm "$1" || die "failed to remove symbolic link"
-        fi
-        if [ -s "$1" ]; then
-            #diff -U3 "$1" "$2" >>/tmp/installed.patch
-            backup "$1"
+        if [ -h "$2" ]; then
+            printf '%s\n' "removing symbolic link $2"
+            rm -- "$2" || die "failed to remove symbolic link"
+        else
+            stash "$1" "$2"
         fi
     fi
 
-    ln "$2" "$1" || die "failed to hardlink $1"
+    ln -- "$1" "$2" || die "failed to create hardlink $2"
 }
 
 softlink_nix() {
-    : "${1:?missing argument}"
-    : "${2:?missing argument}"
-    if [ -e "$1" ]; then
-        if [ -h "$1" ]; then
-            [ "$(exec readlink -- "$1")" != "$2" ] || return 0
-            pl "removing symbolic link $1"
-            rm "$1" || die "failed to remove symbolic link"
+    : "${1:?missing src}"
+    : "${2:?missing dst}"
+    if [ -e "$2" ]; then
+        if [ -h "$2" ]; then
+            [ "$(exec readlink -- "$2")" != "$1" ] || return 0
+            printf '%s\n' "removing symbolic link $2"
+            rm -- "$2" || die "failed to remove symbolic link"
         else
-            die "$1 already exists and is not a symbolic link"
+            die "$2 already exists and is not a symbolic link"
         fi
     fi
 
-    ln -s "$2" "$1" || die "failed to symlink $1"
-}
-
-list_files() {
-    find "${1:-.}" -maxdepth 1 -printf '%P\n' | while read -r f; do
-        [ "${#f}" != 0 ] || continue
-        pl "$f"
-    done
+    ln -s -- "$1" "$2" || die "failed to create symlink $2"
 }
 
 softlink_pseudo() (
-    : "${1:?missing argument}"
-    : "${2:?missing argument}"
-    [ -d "$2" ] || die "$1 is not a directory to softlink"
-    [ -d "$1" ] || mkdir -- "$1" || die "failed to mkdir $1"
+    : "${1:?missing src}"
+    : "${2:?missing dst}"
+    [ -d "$1" ] || die "$1 is not a directory to softlink"
+    [ -d "$2" ] || mkdir -- "$2" || die "failed to make directory $2"
 
-    list_files "$2" | while read -r f; do
-        d1="$1/$f"
-        d2="$2/$f"
+    list_files "$1" | while read -r f; do
+        [ ${#f} != 0 ] || continue
+        d1=$1/$f
+        d2=$2/$f
 
-        if [ -d "$d2" ]; then
-            if [ "$d1" != ".vim/bundle" ]; then # buggy on Windows
-                [ "$VERBOSE" -lt 2 ] || printf '\033[34m / \033[0m %s %s\n' "$d1" "$d2" >&2
+        if [ -d "$d1" ]; then
+            if [ "$d2" != .vim/bundle ]; then # buggy on Windows
+                [ "$VERBOSE" -lt 2 ] || printf '\033[34m / \033[0m %s %s\n' "$d2" "$d1" >&2
                 softlink_pseudo "$d1" "$d2" || exit
             fi
-        elif [ -f "$d2" ]; then
-            [ "$VERBOSE" -lt 2 ] || printf '\033[34m * \033[0m %s\n' "$d1" >&2
+        elif [ -f "$d1" ]; then
+            [ "$VERBOSE" -lt 2 ] || printf '\033[34m * \033[0m %s\n' "$d2" >&2
             hardlink "$d1" "$d2" || exit
         else
-            die "i don't know how to pseudo-symlink $d2"
+            die "i don't know how to pseudo-symlink $d1"
         fi
     done || exit
 )
 
 find_new_files() (
-    : "${1:?missing argument}"
-    : "${2:?missing argument}"
+    : "${1:?missing src}"
+    : "${2:?missing dst}"
+    [ -d "$1" ] || die "$1 is not a directory to compare"
+    [ -d "$2" ] || die "$2 is not a directory to explore"
 
-    list_files "$1" | while read -r f; do
-        d1="$1/$f"
-        d2="$2/$f"
+    list_files "$2" | while read -r f; do
+        [ ${#f} != 0 ] || continue
+        d1=$1/$f
+        d2=$2/$f
 
-        case "$d1" in
+        case $d2 in
         (.vim/.netrwhist) continue;;
         (.vim/backup) continue;;
         (.vim/bundle) continue;;
@@ -108,22 +101,22 @@ find_new_files() (
         (.vim/undo) continue;;
         esac
 
-        if [ -d "$d2" ]; then
+        if [ -d "$d1" ]; then
             find_new_files "$d1" "$d2" || exit
         elif ! [ "$d1" -ef "$d2" ]; then
-            [ -d "$d1" ] && ind=/ || ind=
+            [ -d "$d2" ] && ind=/ || ind=
             if [ "$VERBOSE" -lt 1 ]; then
-                printf ' + %s%s\n' "$d1" "$ind" >&2
+                printf ' + %s%s\n' "$d2" "$ind" >&2
             else
                 #printf 'new destination file. consider manually moving it:\n' >&2
-                printf '\033[32m + \033[0m %s%s\n' "$d1" "$ind" >&2
+                printf '\033[32m + \033[0m %s%s\n' "$d2" "$ind" >&2
             fi
         fi
     done
 )
 
 softlink() {
-    if [ -n "${MSYSTEM-}" ]; then
+    if [ -n "${MSYSTEM:++}" ]; then
         # MSYS2 does not have nor emulate symbolic links.
         softlink_pseudo "$@" || exit
         # to make up for git status not seeing new files:
@@ -134,20 +127,20 @@ softlink() {
 }
 
 readlink -f / >/dev/null || die 'failed sanity check (check your $PATH)'
-rc="$(cd -- "${NAME%/*}/" && pwd -P)" || die "failed to determine rc directory"
+rc=$(cd -- "${program%/*}/" && pwd -P) || die "failed to find rc directory"
 cd -- "${HOME:?parameter null or not set}" || die "failed to change directory"
-backup_dir="$rc/backup-$(exec date -u +%s)" || die "failed to determine date"
+backup_dir=$rc/backup-$(exec date +%s) || die "failed to determine date"
 ! [ -d "$backup_dir" ] || die "backup directory already exists"
 
 for f in \
     .bash_profile .zprofile .profile .bashrc .zshrc .shrc \
     .inputrc .ls_colors .tmux.conf .vimrc .Xresources \
 ; do
-    hardlink "$f" "$rc/home/${f#.}"
+    hardlink "$rc/home/${f#.}" "$f"
 done
 
 for d in sh .vim; do
-    softlink "$d" "$rc/${d#.}"
+    softlink "$rc/${d#.}" "$d"
 done
 
 # create standard XDG directories:
