add script to generate script compatibility tables

diff --git a/regenerate b/regenerate
--- a/regenerate
+++ b/regenerate
@@ -35,14 +35,18 @@ rc="$(readlink -f "$(dirname "$NAME")" )"
 cd "$rc" || die 'failed to change directory'
 
 if ! which git >/dev/null 2>&1; then
-    # git unavailable. just document everything as it is.
-
     [ "$1" != commit ] || die 'git not found'
+
+    # git unavailable. just document everything as it is.
     dash ./sh/document || die 'failed to generate documentation'
+    printf '%s\n' '' '## compatibility' '' >> README.md~ || die 'failed to make room for compatibility table'
+    dash ./tableize >> README.md~ || die 'failed to generate compatibility table'
 
 elif [ "$1" = local ]; then
     # user requested to ignore git.
     dash ./sh/document || die 'failed to generate documentation'
+    printf '%s\n' '' '## compatibility' '' >> README.md~ || die 'failed to make room for compatibility table'
+    dash ./tableize >> README.md~ || die 'failed to generate compatibility table'
 
 else
     # git available. document the most recent commit, without pending changes.
@@ -58,10 +62,11 @@ else
     ln temp/home/-shrc temp/.-shrc || die 'failed to copy files'
     ln temp/home/bashrc temp/.bashrc || die 'failed to copy files'
 
-    # note that we use the latest version instead of the one from the archive.
+    # use new documentation-generating scripts on old shell scripts.
     cp -p README.md temp/README.md || die 'failed to copy existing readme'
-    # note that we use the latest version instead of the one from the archive.
     dash ./sh/document temp || die 'failed to generate documentation'
+    printf '%s\n' '' '## compatibility' '' >> temp/README.md~ || die 'failed to make room for compatibility table'
+    dash ./tableize temp >> temp/README.md~ || die 'failed to generate compatibility table'
 
     #[ ! -e README.md ] || backup README.md || die 'failed to backup existing readme'
     mv temp/README.md~ README.md~ || die 'failed to move generated readme'
