add option to use local files and ignore git

diff --git a/regenerate b/regenerate
--- a/regenerate
+++ b/regenerate
@@ -40,6 +40,10 @@ if ! which git >/dev/null 2>&1; then
     [ "$1" != commit ] || die 'git not found'
     dash ./sh/document || die 'failed to generate documentation'
 
+elif [ "$1" = local ]; then
+    # user requested to ignore git.
+    dash ./sh/document || die 'failed to generate documentation'
+
 else
     # git available. document the most recent commit, without pending changes.
 
