bring `stfu` up to date

diff --git a/sh/stfu b/sh/stfu
--- a/sh/stfu
+++ b/sh/stfu
@@ -38,19 +38,20 @@ stfu() { ### @-
     ###
     ### ```
     argc $# -ge 1 "$0" || return
+    local dirty= err= out= perms= realtemp= ret= tail= temp= time=
 
-    local dirty=0 temp="$STFU_DIR"
-    if [ -z "$temp" ]; then
-        temp="$(mktemp -dt stfu.XXXXXXXXXX)"
-        [ $? -eq 0 ] || { printf '%s\n' "$0: failed create temporary directory" >&2; return 1; }
+    dirty=0 temp="${STFU_DIR-}"
+    if [ -z "${temp:++}" ]; then
+        temp="$(exec mktemp -dt stfu.XXXXXXXXXX)" ||
+        { printf >&2 %s\\n "$0: failed create temporary directory"; return 1; }
         dirty=1
     fi
 
     # NOTE: this stat command will not work on BSD-likes,
     #       but it will work with GNU coreutils and busybox.
-    local perms="$(stat -c '%a' "$temp")"
-    local realtemp="$(readlink -f "$temp")"
-    [ -z "$MSYSTEM" ] || perms=700 # MSYS2 is insecure, oh well.
+    perms="$(exec stat -c %a -- "$temp")"
+    realtemp="$(exec readlink -f -- "$temp")"
+    [ -x /msys2.exe ] && perms=700 # MSYS2 is insecure, oh well.
 
     if [ -d "$temp" ] && [ "$realtemp" = "$temp" ] && [ "$perms" = 700 ]; then
         if [ $dirty -ne 0 ]; then
@@ -58,32 +59,29 @@ stfu() { ### @-
         fi
     else
         if [ -n "$STFU_DIR" ]; then
-            printf '%s\n' "$0: invalid temporary directory, please unset STFU_DIR" >&2
+            printf >&2 %s\\n "$0: invalid temporary directory, please unset STFU_DIR"
         else
-            printf '%s\n' "$0: something went horribly wrong, maybe you can tell?" "$perms" "$realtemp" >&2
+            printf >&2 %s\\n "$0: something went horribly wrong, maybe you can tell?" "$perms" "$realtemp"
         fi
         return 1
     fi
 
-    local time="$(date -u '+%s')"
-    [ $? -eq 0 ] || { printf '%s\n' "$0: failed to get current time" >&2; return 1; }
+    time="$(exec date +%s)" ||
+    { printf >&2 %s\\n "$0: failed to get current time"; return 1; }
 
-    mkdir -p "$temp" || { printf '%s\n' "$0: failed to create temp directory" >&2; return 1; }
+    mkdir -p "$temp" ||
+    { printf >&2 %s\\n "$0: failed to create temp directory"; return 1; }
 
     while [ -e "$temp/out_$time" ] || [ -e "$temp/err_$time" ]; do time=$((time+1)); done
-    local out="$temp/out_$time"
-    local err="$temp/err_$time"
+    out="$temp/out_$time"
+    err="$temp/err_$time"
 
-    touch "$out" && touch "$err" || { printf '%s\n' "$0: failed to create temp files" >&2; return 1; }
+    touch -- "$out" "$err" ||
+    { printf >&2 %s\\n "$0: failed to create temp files"; return 1; }
 
-    #local out="$(mktemp -t -p "$temp" out_XXXXXX)"
-    #[ $? -eq 0 ] || { printf '%s\n' "$0: failed to create temp file" >&2; return 1; }
-    #local err="$(mktemp -t -p "$temp" err_XXXXXX)"
-    #[ $? -eq 0 ] || { printf '%s\n' "$0: failed to create temp file" >&2; return 1; }
-
-    local ret=0 tail="${STFU_TAIL:-20}"
-    "$@" > "$out" 2> "$err" || ret=$?
-    if [ $ret -ne 0 ]; then
+    ret=0 tail="${STFU_TAIL:-20}"
+    "$@" >| "$out" 2>| "$err" || ret=$?
+    if [ $ret != 0 ]; then
         printf 'command failed with exit status %s:\n' $ret >&2
         echo2 "$@"
         echo2
